services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./server/.env.development
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  api:
    container_name: api
    build: ./server
    ports:
      - 8888:8888
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - server/.env.development

  next-app:
    container_name: next-app
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - postgres
      - api
      - next-app

volumes:
  postgres-volume: